### ISSUE TITLE
🐞 - Site not loading

### ISSUE THREAD

**Issue by hadiyarajesh** [riccardoperra/codeimage#575] opened 2023-11-22 18:02 UTC
### Which @codeimage/* package(s) are the source of the bug?

codeimage

### Please provide a screenshot or a video to a minimal reproduction of the bug

https://app.codeimage.dev site not loading

### Description

Trying to load the site, but it's not working. Only loading animation is shown on laptop (working fine on mobile devices). Tried on multiple browser/multiple systems but not working. Only error I can see in network inspector is "cascadia font not loading"

<img width="1467" alt="Screenshot 2023-11-22 at 11 32 21 PM" src="https://github.com/riccardoperra/codeimage/assets/12107428/2eb1c150-06cb-4191-a727-63a640995228">

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [X] Edge

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [X] Android

**Comment by riccardoperra** [comment] 2023-11-22 18:21
Hi, i'm not able to reproduce that issue neither in window and mac. Do you have any installed extension in your browser? Sometimes adblockers prevent to download some resources. The loading font that you're trying to download is an external resource and it's answering with 200 to me. Do you have any other error in your console? 

Anyway, can you try to clear the cache of both local storage and indexedDB?

![image](https://github.com/riccardoperra/codeimage/assets/37072694/40338bc2-05e4-4c40-83a0-f55a044c4c73)

**Comment by hadiyarajesh** [comment] 2023-11-23 02:07
Yes, it solved in chrome now. It still gives errors in safari, but that'll be fine. Thank you (+1 Thank you for creating code image ❤️)

**Comment by riccardoperra** [comment] 2023-11-23 05:36
What version of safari do you use?

**Comment by hadiyarajesh** [comment] 2023-11-23 07:58
> What version of safari do you use?

Version 17.1 (19616.2.9.11.7) with AdGuard for safari. (Although Chrome with uBlock origin worked)

**Comment by riccardoperra** [comment] 2023-11-23 08:11
I'll do a check soon since i'm waiting for a new macbook 😄 Currently I can test only on safari 16. 

Anyway thanks for reaching me 😄 I'm reopening this issue just as reminder

**Comment by riccardoperra** [comment] 2023-12-31 11:03
Hi, after an investigation I'm not able to reproduce that issue even with AdGuard for safari (Version 17.2.1 (19617.1.17.11.12)).

<img width="1890" alt="Screenshot 2023-12-31 alle 12 01 04" src="https://github.com/riccardoperra/codeimage/assets/37072694/d2444d88-5ffa-4a15-8ab0-43121817ff1f">

I saw that the network URL were "fon2ts.googleapis.com" but it should be fonts.googleapis.com. Don't know what's causing this.

I'm closing that issue at the moment but if the error is still present just ping me.

**Closed by riccardoperra** 2023-12-31 11:03 UTC
Labels: bug, P1
